// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: cornucopia.proto

package cornucopia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                 // User or Project ID from Dashboard
	CanOverdraft  bool                   `protobuf:"varint,2,opt,name=can_overdraft,json=canOverdraft,proto3" json:"can_overdraft,omitempty"` // Whether the account can go negative
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_cornucopia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateAccountRequest) GetCanOverdraft() bool {
	if x != nil {
		return x.CanOverdraft
	}
	return false
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CanOverdraft  bool                   `protobuf:"varint,4,opt,name=can_overdraft,json=canOverdraft,proto3" json:"can_overdraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_cornucopia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateAccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountResponse) GetCanOverdraft() bool {
	if x != nil {
		return x.CanOverdraft
	}
	return false
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_cornucopia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CanOverdraft  bool                   `protobuf:"varint,4,opt,name=can_overdraft,json=canOverdraft,proto3" json:"can_overdraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_cornucopia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetAccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAccountResponse) GetCanOverdraft() bool {
	if x != nil {
		return x.CanOverdraft
	}
	return false
}

type TransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId  string                 `protobuf:"bytes,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId    string                 `protobuf:"bytes,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_cornucopia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *TransferRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TransferResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JournalEntryId string                 `protobuf:"bytes,1,opt,name=journal_entry_id,json=journalEntryId,proto3" json:"journal_entry_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_cornucopia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{5}
}

func (x *TransferResponse) GetJournalEntryId() string {
	if x != nil {
		return x.JournalEntryId
	}
	return ""
}

func (x *TransferResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetJournalEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJournalEntriesRequest) Reset() {
	*x = GetJournalEntriesRequest{}
	mi := &file_cornucopia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalEntriesRequest) ProtoMessage() {}

func (x *GetJournalEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetJournalEntriesRequest) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{6}
}

func (x *GetJournalEntriesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetJournalEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetJournalEntriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetJournalEntriesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JournalEntries []*JournalEntry        `protobuf:"bytes,1,rep,name=journal_entries,json=journalEntries,proto3" json:"journal_entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetJournalEntriesResponse) Reset() {
	*x = GetJournalEntriesResponse{}
	mi := &file_cornucopia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalEntriesResponse) ProtoMessage() {}

func (x *GetJournalEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetJournalEntriesResponse) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{7}
}

func (x *GetJournalEntriesResponse) GetJournalEntries() []*JournalEntry {
	if x != nil {
		return x.JournalEntries
	}
	return nil
}

type JournalEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JournalEntryId string                 `protobuf:"bytes,1,opt,name=journal_entry_id,json=journalEntryId,proto3" json:"journal_entry_id,omitempty"`
	FromAccountId  string                 `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId    string                 `protobuf:"bytes,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_cornucopia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{8}
}

func (x *JournalEntry) GetJournalEntryId() string {
	if x != nil {
		return x.JournalEntryId
	}
	return ""
}

func (x *JournalEntry) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *JournalEntry) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *JournalEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *JournalEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JournalEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_cornucopia_proto protoreflect.FileDescriptor

const file_cornucopia_proto_rawDesc = "" +
	"\n" +
	"\x10cornucopia.proto\x12\x06plutus\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x14CreateAccountRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12#\n" +
	"\rcan_overdraft\x18\x02 \x01(\bR\fcanOverdraft\"\x90\x01\n" +
	"\x15CreateAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12#\n" +
	"\rcan_overdraft\x18\x04 \x01(\bR\fcanOverdraft\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x8d\x01\n" +
	"\x12GetAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12#\n" +
	"\rcan_overdraft\x18\x04 \x01(\bR\fcanOverdraft\"\xc0\x01\n" +
	"\x0fTransferRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\tR\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"w\n" +
	"\x10TransferResponse\x12(\n" +
	"\x10journal_entry_id\x18\x01 \x01(\tR\x0ejournalEntryId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"g\n" +
	"\x18GetJournalEntriesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Z\n" +
	"\x19GetJournalEntriesResponse\x12=\n" +
	"\x0fjournal_entries\x18\x01 \x03(\v2\x14.plutus.JournalEntryR\x0ejournalEntries\"\xf9\x01\n" +
	"\fJournalEntry\x12(\n" +
	"\x10journal_entry_id\x18\x01 \x01(\tR\x0ejournalEntryId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\tR\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xc7\x02\n" +
	"\x11CornucopiaService\x12N\n" +
	"\rCreateAccount\x12\x1c.plutus.CreateAccountRequest\x1a\x1d.plutus.CreateAccountResponse\"\x00\x12E\n" +
	"\n" +
	"GetAccount\x12\x19.plutus.GetAccountRequest\x1a\x1a.plutus.GetAccountResponse\"\x00\x12?\n" +
	"\bTransfer\x12\x17.plutus.TransferRequest\x1a\x18.plutus.TransferResponse\"\x00\x12Z\n" +
	"\x11GetJournalEntries\x12 .plutus.GetJournalEntriesRequest\x1a!.plutus.GetJournalEntriesResponse\"\x00BQ\n" +
	"\x12jp.trap.plutus.apiB\x06PlutusP\x01Z1github.com/traP-jp/plutus/api/protobuf;cornucopiab\x06proto3"

var (
	file_cornucopia_proto_rawDescOnce sync.Once
	file_cornucopia_proto_rawDescData []byte
)

func file_cornucopia_proto_rawDescGZIP() []byte {
	file_cornucopia_proto_rawDescOnce.Do(func() {
		file_cornucopia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cornucopia_proto_rawDesc), len(file_cornucopia_proto_rawDesc)))
	})
	return file_cornucopia_proto_rawDescData
}

var file_cornucopia_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cornucopia_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),      // 0: plutus.CreateAccountRequest
	(*CreateAccountResponse)(nil),     // 1: plutus.CreateAccountResponse
	(*GetAccountRequest)(nil),         // 2: plutus.GetAccountRequest
	(*GetAccountResponse)(nil),        // 3: plutus.GetAccountResponse
	(*TransferRequest)(nil),           // 4: plutus.TransferRequest
	(*TransferResponse)(nil),          // 5: plutus.TransferResponse
	(*GetJournalEntriesRequest)(nil),  // 6: plutus.GetJournalEntriesRequest
	(*GetJournalEntriesResponse)(nil), // 7: plutus.GetJournalEntriesResponse
	(*JournalEntry)(nil),              // 8: plutus.JournalEntry
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_cornucopia_proto_depIdxs = []int32{
	9, // 0: plutus.TransferResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: plutus.GetJournalEntriesResponse.journal_entries:type_name -> plutus.JournalEntry
	9, // 2: plutus.JournalEntry.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: plutus.CornucopiaService.CreateAccount:input_type -> plutus.CreateAccountRequest
	2, // 4: plutus.CornucopiaService.GetAccount:input_type -> plutus.GetAccountRequest
	4, // 5: plutus.CornucopiaService.Transfer:input_type -> plutus.TransferRequest
	6, // 6: plutus.CornucopiaService.GetJournalEntries:input_type -> plutus.GetJournalEntriesRequest
	1, // 7: plutus.CornucopiaService.CreateAccount:output_type -> plutus.CreateAccountResponse
	3, // 8: plutus.CornucopiaService.GetAccount:output_type -> plutus.GetAccountResponse
	5, // 9: plutus.CornucopiaService.Transfer:output_type -> plutus.TransferResponse
	7, // 10: plutus.CornucopiaService.GetJournalEntries:output_type -> plutus.GetJournalEntriesResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cornucopia_proto_init() }
func file_cornucopia_proto_init() {
	if File_cornucopia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cornucopia_proto_rawDesc), len(file_cornucopia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cornucopia_proto_goTypes,
		DependencyIndexes: file_cornucopia_proto_depIdxs,
		MessageInfos:      file_cornucopia_proto_msgTypes,
	}.Build()
	File_cornucopia_proto = out.File
	file_cornucopia_proto_goTypes = nil
	file_cornucopia_proto_depIdxs = nil
}
