// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: cornucopia.proto

package plutus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cornucopia_Ping_FullMethodName = "/proto.Cornucopia/Ping"
)

// CornucopiaClient is the client API for Cornucopia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CornucopiaClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type cornucopiaClient struct {
	cc grpc.ClientConnInterface
}

func NewCornucopiaClient(cc grpc.ClientConnInterface) CornucopiaClient {
	return &cornucopiaClient{cc}
}

func (c *cornucopiaClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Cornucopia_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CornucopiaServer is the server API for Cornucopia service.
// All implementations must embed UnimplementedCornucopiaServer
// for forward compatibility.
type CornucopiaServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedCornucopiaServer()
}

// UnimplementedCornucopiaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCornucopiaServer struct{}

func (UnimplementedCornucopiaServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCornucopiaServer) mustEmbedUnimplementedCornucopiaServer() {}
func (UnimplementedCornucopiaServer) testEmbeddedByValue()                    {}

// UnsafeCornucopiaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CornucopiaServer will
// result in compilation errors.
type UnsafeCornucopiaServer interface {
	mustEmbedUnimplementedCornucopiaServer()
}

func RegisterCornucopiaServer(s grpc.ServiceRegistrar, srv CornucopiaServer) {
	// If the following call panics, it indicates UnimplementedCornucopiaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cornucopia_ServiceDesc, srv)
}

func _Cornucopia_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CornucopiaServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cornucopia_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CornucopiaServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Cornucopia_ServiceDesc is the grpc.ServiceDesc for Cornucopia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cornucopia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Cornucopia",
	HandlerType: (*CornucopiaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Cornucopia_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cornucopia.proto",
}
