// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cornucopia.proto

package plutus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_cornucopia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latency       int64                  `protobuf:"varint,1,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_cornucopia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_cornucopia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_cornucopia_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetLatency() int64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

var File_cornucopia_proto protoreflect.FileDescriptor

const file_cornucopia_proto_rawDesc = "" +
	"\n" +
	"\x10cornucopia.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\aRequest\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"$\n" +
	"\bResponse\x12\x18\n" +
	"\alatency\x18\x01 \x01(\x03R\alatency27\n" +
	"\n" +
	"Cornucopia\x12)\n" +
	"\x04Ping\x12\x0e.proto.Request\x1a\x0f.proto.Response\"\x00B5\n" +
	"\x0ejp.trap.plutusB\x06PlutusP\x01Z\x19github.com/traP-jp/plutusb\x06proto3"

var (
	file_cornucopia_proto_rawDescOnce sync.Once
	file_cornucopia_proto_rawDescData []byte
)

func file_cornucopia_proto_rawDescGZIP() []byte {
	file_cornucopia_proto_rawDescOnce.Do(func() {
		file_cornucopia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cornucopia_proto_rawDesc), len(file_cornucopia_proto_rawDesc)))
	})
	return file_cornucopia_proto_rawDescData
}

var file_cornucopia_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cornucopia_proto_goTypes = []any{
	(*Request)(nil),               // 0: proto.Request
	(*Response)(nil),              // 1: proto.Response
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_cornucopia_proto_depIdxs = []int32{
	2, // 0: proto.Request.date:type_name -> google.protobuf.Timestamp
	0, // 1: proto.Cornucopia.Ping:input_type -> proto.Request
	1, // 2: proto.Cornucopia.Ping:output_type -> proto.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cornucopia_proto_init() }
func file_cornucopia_proto_init() {
	if File_cornucopia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cornucopia_proto_rawDesc), len(file_cornucopia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cornucopia_proto_goTypes,
		DependencyIndexes: file_cornucopia_proto_depIdxs,
		MessageInfos:      file_cornucopia_proto_msgTypes,
	}.Build()
	File_cornucopia_proto = out.File
	file_cornucopia_proto_goTypes = nil
	file_cornucopia_proto_depIdxs = nil
}
